### ISSUE TITLE
The weights file best.pt is not available.

### ISSUE THREAD

**Issue by qingzi02010** [MarkDana/RealtimeConeDetection#3]

**Comment by fengxueem** [comment]
Also found this problem.The weights file best.pt cannot be downloaded from https://jbox.sjtu.edu.cn/l/wJoO64.
Dear project owner, maybe try to use pan.baidu.com to share this best.pt?

**Comment by alex-lougheed4** [comment]
> Also found this problem.The weights file best.pt cannot be downloaded from https://jbox.sjtu.edu.cn/l/wJoO64. Dear project owner, maybe try to use pan.baidu.com to share this best.pt?

Did you happen to find the weights file by any chance or a suitable replacement? @fengxueem

**Comment by fengxueem** [comment]
@alex-lougheed4 Yes. I have sent an Email to the project owner. He gave me a copy of best.pt. You may try the same action.

**Comment by MarkDana** [comment]
@alex-lougheed4 @qingzi02010 Sorry for the inconvenience brought. I haven't paid attention to the maintenence of this repo for long. `best.pt` has been updated [here](https://drive.google.com/file/d/1cTnrWIjWcGjLzz44P6cCUxqh8teCaoFr/view?usp=sharing). So sorry for the late reply!
