### ISSUE TITLE
data set missing 

### ISSUE THREAD

**Issue by PSmith4** [MarkDana/RealtimeConeDetection#4]
is the Jbox link not working any more?

**Comment by khaghanijavad** [comment]
Hi, thanks for releasing this project. 
Could you please provide a new link to the dataset as the existing Jbox one is not working?

**Comment by MarkDana** [comment]
@PSmith4 @khaghanijavad Sorry for the inconvenience brought. I haven't paid attention to the maintenence of this repo for long. Labelled cones dataset has been updated [here](https://drive.google.com/file/d/1YiIPC1m8EDJyj5R7FV5hyRAjHOe9_Bmd/view?usp=sharing). So sorry for the late reply!
